# Generated by Django 3.2.6 on 2021-08-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.TextField(),
        ),
    ]
